name: Markdown-related Check

on:
  pull_request:
    branches: "*"

jobs:
  markdown-related-check:
    name: markdown-related check
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Markdown Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: 'main'
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
          check-modified-files-only: 'yes'
          config-file: '.github/workflows/.mlc_config.json'

      - name: Markdown Lint Check
        uses: docker://dragonflyoss/linter:v0.2.7
        with:
          # lint all markdown files excluding vendor folder
          args: bash -c "find ./ -name '*.md' | grep -v vendor | grep -v .github | grep -v index.md | grep -v docs/commandline | xargs mdl -r ~MD010,~MD013,~MD022,~MD024,~MD026,~MD029,~MD033,~MD036"


